### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by JiJiang233** [TaoismDeepLake/Genshin12#1]
钟离的蓄力技能受到伤害之后会累加效果等级并且剩余时间翻倍

**Comment by TaoismDeepLake** [comment]
效果等级提升是正常的，因为钟离的护盾受击后会提升护盾强效；剩余时间我抽空看下

**Comment by TaoismDeepLake** [comment]
已在0.4.8解决时间异常。
Zhongli Shield duration error on hit. Resolved in 0.4.8
